name: rwg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - plyfile=1.0.3
  - python=3.10
  - pip=22.3.1
  - mkl=2024.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  # - pytorch-cuda=11.8
  - tqdm
  - pip:
    - open3d==0.18.0
    - einops
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn